---
name: Build and Publish
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run tests
        env:
          CI: true
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.8
        with:
          tag_name: 'v%s'
          tag_message: 'v%s'
          commit_pattern: "^Release (\\S+)"
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.NODE_GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
