---
name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.NODE_GITHUB_TOKEN }}
          title: 'Release {tag}'
          exclude: true
          commit-template: '- {title} ← {hash}'
          template: |
            ### Changelog

            {commits}

            {range}
