---
name: Run tests
on:
  pull_request:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run tests
